trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - refs/tags/*
pr:
  autoCancel: true
  branches:
    include:
      - master

resources:
  repositories:
    - repository: rsg
      type: github
      name: RocketSurgeonsGuild/AzureDevopsTemplates
      ref: refs/tags/v0.11.3
      endpoint: github

variables:
  - group: rsg-bot
  - name: CONFIGURATION
    value: Release
  - name: VERBOSITY
    value: Normal
  - name: COVERAGE
    value: "$(Agent.BuildDirectory)/c"
  - name: ARTIFACTS
    value: $(Build.ArtifactStagingDirectory)
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: "true"
  - name: CodeCovToken
    value: '6502eb14-343a-43eb-96f4-d282791a48b3'

jobs:
  - template: pipeline/nuke.yml@rsg
    parameters:
      name: 'Build'
      dependsOn: GitVersion
      vmImage: "macOS-10.14"
      Configuration: $(Configuration)
      Verbosity: $(Verbosity)
      GitHubPackages: true
      EnableReleaseNotes: false
      DotNetSdk:
        - "2.x"
        - "3.x"
      NuGetVersion: "5.2.0"
      PublishNuGetPackages: 'Windows'
      Matrix:
        Windows:
          BuildName: "Windows"
          ImageName: "Windows-latest"